string name
string entry
string exit
string time_ref
float32 earliest_entry
float32 latest_entry
---
bool success
string reason
string id
string time_ref
float32 earliest_entry
float32 latest_entry
float32 earliest_exit
float32 latest_exit
int32[] shape
uint8[] corridor